<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Smart_Freelance_API</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="Hangfire" Version="1.8.21" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.21" />
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="9.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NSwag.Generation" Version="14.6.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.2" />
    <PackageReference Include="Xdot.Paymob.CashIn.DependencyInjection" Version="1.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Smart-Freelance-Core\Smart-Freelance-Core.csproj" />
    <ProjectReference Include="..\Smart-Freelance-Infrastructure\Smart-Freelance-Infrastructure.csproj" />
  </ItemGroup>

</Project>
