name: Deploy Smart Freelance API

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore Smart-Freelance-API/Smart-Freelance-API.csproj

      - name: Build
        run: dotnet build Smart-Freelance-API/Smart-Freelance-API.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish Smart-Freelance-API/Smart-Freelance-API.csproj --configuration Release --no-build --output ./publish --runtime win-x86

      - name: Deploy to MonsterASP.NET
        uses: rasmusbuchholdt/simply-web-deploy@2.1.0
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}