<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Smart_Freelance_Core</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Features\Messages\Commands\" />
    <Folder Include="Features\Projects\Queries\GetProjectPaginated\" />
    <Folder Include="Features\Proposals\Queries\" />
    <Folder Include="Mapping\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Routing.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="RabbitMQ.Client" Version="7.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Smart-Freelance-Data\Smart-Freelance-Data.csproj" />
    <ProjectReference Include="..\Smart-Freelance-Infrastructure\Smart-Freelance-Infrastructure.csproj" />
    <ProjectReference Include="..\Smart-Freelance-Service\Smart-Freelance-Service.csproj" />
  </ItemGroup>

</Project>
