<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Smart_Freelance_Infrastructure</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Implementations\" />
    <Folder Include="Abstracts\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.10" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="7.3.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="7.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Smart-Freelance-Data\Smart-Freelance-Data.csproj" />
  </ItemGroup>

</Project>
